### ISSUE TITLE
App not displaying correctly for bedrock servers

### ISSUE THREAD

**Issue by benshan36** [eclair4151/MC-Status-Widget-for-Minecraft#39]
The app was working fine for me for a while, and then a few months ago it started displaying the info incorrectly. It is showing version as the number of players, MOTD shows the protocol and game mode, and number of players just says 20/0 constantly. Please fix this
![IMG_3543](https://github.com/user-attachments/assets/43d31ec3-70e4-4357-b8bb-0fc85ba57c58)

**Comment by eclair4151** [comment]
Thanks ofr the report, I think I've fixed this in my latest update, do you mind emailing me the server details, so I can confirm the fix on my end? tomerjshemesh@gmail.com

Thanks!

**Comment by benshan36** [comment]
Yes I’ll send you the info. Thank you so much!

**Comment by eclair4151** [comment]
This was due to parsing bug, I incorrectly assumed 
`stringInput.split(separator:` ";") 

would preserve blank strings where double ;; appeared, but I had to instead specify
`stringInput.split(separator:` ";", omittingEmptySubsequences: false)



https://github.com/eclair4151/MC-Status-Widget-for-Minecraft/blob/92f34dcbe6fced83f2eb25ea063b5d25aa64907f/MinecraftServerStatus/Helpers/StatusChecker.swift#L299

**Comment by eclair4151** [comment]
This is now complete. You can test the new 2.0 version of the app here on testflight before release:

WARNING!! There is currently a bug that means you will have to delete and re-add your widgets if you try out the new beta. This should be resolved before release but I didnt want to hold up testing.

https://testflight.apple.com/join/UqHNAYJn

**Comment by benshan36** [comment]
Yes, the bug was still prevalent for me as well but only a minor
inconvenience. The app rebuild looks great! And my server displays its
information properly again. Thank you so much
